# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "052e481ca8c82ba4104b83ce5abaa6a360e39edffd0e6b3da51331aea8291bf9"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d769ded9a68ff2811a47491de2dd106f76c29aaca193f2c6a34c13c4e7e54bc2"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eed1afd3fd299e958fa28013035b17e2de4019a5b283003f69b4dab6a9f70462"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38892b44a474241965d810af6ea736175158d9c683a0e60d897ea62e7657dcdb"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required

end
