# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "0.2.36"

  on_macos do
    on_intel do
      sha256 "b6646ce77b75e4548f66b4b51d27ba6c2728e3346c6efec8e849deb3f02ffae1"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4012157eb684be7f58fc05a6aa3eb8fece44051707bc74811a67baaad65e17f0"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95d8d371288fb4adeb4cd1ab230e28ea4b98a82cabda03f205614fe935332ab5"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a3b4a694211118bb13e1558d1f4084e34b71e2d86bd54e6c866e243e1a33e333"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required

end
