# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "8a4f791db3693c22811ce69cfb7c55a60004eb9faf481aab440120c709294562"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e527aa7160eb93f0f5867b121d2d0f65f1c6231f9dfba2dd786b5294ecf4697a"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2bbdb839c147692dbcfb51bdb935ab7c1d67b397cea452d5a7a18b3156f2093e"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6f98d55725405fc8dc71370a7d55e9cc94754f6a23721aafba46d6fb9913a3e6"
      url "https://github.com/flightcontrolhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required

end
