# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ravion < Formula
  desc "Ravion CLI"
  homepage "https://ravion.com"
  version "0.0.1-rc.2"
  license "FSL-1.1-MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flightcontrolhq/cli/releases/download/v0.0.1-rc.2/ravion_0.0.1-rc.2_darwin_x86_64.tar.gz"
      sha256 "e36735d936ffff415c1c782fd2f712c5e0093ac4c7c6fc23bd4d8e01889b1067"

      define_method(:install) do
        bin.install "ravion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flightcontrolhq/cli/releases/download/v0.0.1-rc.2/ravion_0.0.1-rc.2_darwin_arm64.tar.gz"
      sha256 "453f199e2641f733a2ea2b35d4fc0489c87c3c0311dd3b624e6b0d29954bb3d2"

      define_method(:install) do
        bin.install "ravion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flightcontrolhq/cli/releases/download/v0.0.1-rc.2/ravion_0.0.1-rc.2_linux_x86_64.tar.gz"
      sha256 "0763d04fc947d2dd722f6bff185560ad1837ae579c25106e416295829040b57e"
      define_method(:install) do
        bin.install "ravion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flightcontrolhq/cli/releases/download/v0.0.1-rc.2/ravion_0.0.1-rc.2_linux_arm64.tar.gz"
      sha256 "a9a1b52f2a67c9c0ffcf07bf630fe2aad9e0f7438b8127888531331c4d4f6c86"
      define_method(:install) do
        bin.install "ravion"
      end
    end
  end

  test do
    system "#{bin}/ravion --version"
  end
end
